# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf44bdd59f8875aa3def7135d16c190f3264e9e6e88853c9ae1518a5e49c8828a6c00c9740249308ffddb009c3e1abf0483e9c34f2a81a19443b51be0f34aa22

test:
  secret_key_base: a744ecaf208c91eee126bc05c4d234d9762b1c8a4eae06d2c5a898ab315fef90012fc2da29630f4e1615b527374cf7ea5a6abfabf06276ae853c0af9e3808560

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
